language: cpp

os:
  - windows
  - linux

compiler:
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x install_depend_linux.sh && ./install_depend_linux.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then chmod +x install_depend_windows.sh && ./install_depend_windows.sh ; fi

install:
  - mkdir "build_${TRAVIS_OS_NAME}"
  - cd "build_${TRAVIS_OS_NAME}"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -DCMAKE_INSTALL_PREFIX=/tmp/linux .. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cmake -DCMAKE_TOOLCHAIN_FILE=mingw32.cmake -DCMAKE_INSTALL_PREFIX=/tmp/mingw32 .. ; fi
  - make && make install
